image: node:20.13.1-alpine3.20

stages:
  - test
  - build
  - publish

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/
    - .npm/
  policy: pull-push

install_dependencies:
  stage: test
  script:
    - npm ci --legacy-peer-deps --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules/
  tags:
    - group

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  dependencies:
    - install_dependencies
  tags:
    - group

publish:
  stage: publish
  script:
    - test -n "$CI_JOB_TOKEN" || { echo "Missing CI_JOB_TOKEN"; exit 1; }
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - npm publish
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_TAG # Ensures it runs only for tags
  tags:
    - group
