image: node:20.13.1-alpine3.20

before_script:
  - npm install -g pnpm
  - pnpm config set @org:registry https://gitlab.com/api/v4/packages/npm/
  - pnpm config set '//gitlab.com/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"

stages:
  - test
  - build
  - publish

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_REF_PROTECTED == "true"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .pnpm-store

install_dependencies:
  stage: test
  script:
    - pnpm install
  artifacts:
    paths:
      - node_modules/
  tags:
    - group

build:
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - dist/
  dependencies:
    - install_dependencies
  tags:
    - group

publish:
  stage: publish
  script:
    - test -n "$CI_JOB_TOKEN" || { echo "Missing CI_JOB_TOKEN"; exit 1; }
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - pnpm publish --no-git-checks
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_TAG # Ensures it runs only for tags
  tags:
    - group
