default:
  image: node:latest

stages:
  - deploy

publish-npm:
  stage: deploy
  script:
    - echo "@qualif:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
# image: node:16

# stages:
#   - test
#   - build
#   - publish

# cache:
#   paths:
#     - node_modules/

# install_dependencies:
#   stage: test
#   script:
#     - npm ci --legacy-peer-deps
#   artifacts:
#     paths:
#       - node_modules/

# lint:
#   stage: test
#   script:
#     - npm run lint
#   dependencies:
#     - install_dependencies

# build:
#   stage: build
#   script:
#     - npm run build
#   artifacts:
#     paths:
#       - dist/
#   dependencies:
#     - install_dependencies

# publish:
#   stage: publish
#   script:
#     - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
#     - npm publish
#   dependencies:
#     - build
#   only:
#     - tags
